import { requestStatus } from "../helpers/constants";

export const raisedRetentionRequests = [
  {
    profile: {
      name: "Yuvika Jain",
      profileImage:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtsSbrsoLNPyAUwVkiNfnQsf6d-xPwtXjDZ-NGyZxzHQ&s",
      employeeId: "1109645624364",
    },
    id: 1,
    email: "yuvika.jain@hexaware.com",
    grade: "G5",
    experience: "15 years",
    status: requestStatus.APPROVED,
    designation: "Associate Software Engineer",
    phone: "+91 8687326487",
    reportingManager: "P venkat Raman",
    projects: "HDFC, EY",
    requestStatusStep: 3,
  },
  {
    profile: {
      name: "John Doe",
      profileImage:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtsSbrsoLNPyAUwVkiNfnQsf6d-xPwtXjDZ-NGyZxzHQ&s",
      employeeId: "1234567890",
    },
    id: 2,
    email: "john.doe@example.com",
    grade: "G4",
    experience: "10 years",
    status: requestStatus.OPEN,
    designation: "Senior Software Engineer",
    phone: "+1 1234567890",
    reportingManager: "Jane Smith",
    projects: "ABC Corp, XYZ Corp",
    requestStatusStep: 2,
  },
  {
    profile: {
      name: "Jane Smith",
      profileImage:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtsSbrsoLNPyAUwVkiNfnQsf6d-xPwtXjDZ-NGyZxzHQ&s",
      employeeId: "9876543210",
    },
    id: 3,
    email: "jane.smith@example.com",
    grade: "G6",
    experience: "20 years",
    status: requestStatus.REJECTED,
    designation: "Principal Software Engineer",
    phone: "+1 9876543210",
    reportingManager: "Michael Johnson",
    projects: "PQR Corp, MNO Corp",
    requestStatusStep: 4,
  },
  {
    profile: {
      name: "David Wilson",
      profileImage:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtsSbrsoLNPyAUwVkiNfnQsf6d-xPwtXjDZ-NGyZxzHQ&s",
      employeeId: "2468135790",
    },
    id: 4,
    email: "david.wilson@example.com",
    grade: "G3",
    experience: "7 years",
    status: requestStatus.APPROVED,
    designation: "Software Engineer",
    phone: "+1 2345678901",
    reportingManager: "Sarah Thompson",
    projects: "LMN Corp, GHI Corp",
    requestStatusStep: 3,
  },
  {
    profile: {
      name: "Sarah Thompson",
      profileImage:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtsSbrsoLNPyAUwVkiNfnQsf6d-xPwtXjDZ-NGyZxzHQ&s",
      employeeId: "1357924680",
    },
    id: 5,
    email: "sarah.thompson@example.com",
    grade: "G7",
    experience: "22 years",
    status: requestStatus.OPEN,
    designation: "Lead Software Engineer",
    phone: "+1 3456789012",
    reportingManager: "Robert Davis",
    projects: "JKL Corp, DEF Corp",
    requestStatusStep: 2,
  },
  {
    profile: {
      name: "Sophia Thompson",
      profileImage: "https://example.com/profiles/sophiathompson.jpg",
      employeeId: "7359146208",
    },
    id: 11,
    email: "sophia.thompson@example.com",
    grade: "G4",
    experience: "11 years",
    status: requestStatus.OPEN,
    designation: "Senior Software Engineer",
    phone: "+1 9012345678",
    reportingManager: "Christopher Davis",
    projects: "ABC Corp, LMN Corp",
    requestStatusStep: 2,
  },
  {
    profile: {
      name: "Christopher Davis",
      profileImage:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtsSbrsoLNPyAUwVkiNfnQsf6d-xPwtXjDZ-NGyZxzHQ&s",
      employeeId: "2089134576",
    },
    id: 12,
    email: "christopher.davis@example.com",
    grade: "G6",
    experience: "16 years",
    status: requestStatus.APPROVED,
    designation: "Lead Software Engineer",
    phone: "+1 2345678901",
    reportingManager: "Jennifer Wilson",
    projects: "XYZ Corp, ABC Corp",
    requestStatusStep: 3,
  },
  {
    profile: {
      name: "Jennifer Wilson",
      profileImage:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtsSbrsoLNPyAUwVkiNfnQsf6d-xPwtXjDZ-NGyZxzHQ&s",
      employeeId: "9134675208",
    },
    id: 13,
    email: "jennifer.wilson@example.com",
    grade: "G7",
    experience: "19 years",
    status: requestStatus.REJECTED,
    designation: "Principal Software Engineer",
    phone: "+1 3456789012",
    reportingManager: "Steven Thompson",
    projects: "LMN Corp, DEF Corp",
    requestStatusStep: 4,
  },
  {
    profile: {
      name: "Steven Thompson",
      profileImage:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtsSbrsoLNPyAUwVkiNfnQsf6d-xPwtXjDZ-NGyZxzHQ&s",
      employeeId: "5208913467",
    },
    id: 14,
    email: "steven.thompson@example.com",
    grade: "G5",
    experience: "13 years",
    status: requestStatus.APPROVED,
    designation: "Associate Software Engineer",
    phone: "+1 4567890123",
    reportingManager: "Laura Davis",
    projects: "DEF Corp, JKL Corp",
    requestStatusStep: 3,
  },
  {
    profile: {
      name: "Laura Davis",
      profileImage:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtsSbrsoLNPyAUwVkiNfnQsf6d-xPwtXjDZ-NGyZxzHQ&s",
      employeeId: "3467920813",
    },
    id: 15,
    email: "laura.davis@example.com",
    grade: "G4",
    experience: "10 years",
    status: requestStatus.OPEN,
    designation: "Software Engineer",
    phone: "+1 5678901234",
    reportingManager: "Matthew Wilson",
    projects: "ABC Corp, XYZ Corp",
    requestStatusStep: 2,
  },
  {
    profile: {
      name: "Jane Smith",
      profileImage:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtsSbrsoLNPyAUwVkiNfnQsf6d-xPwtXjDZ-NGyZxzHQ&s",
      employeeId: "9876543210",
    },
    id: 3,
    email: "jane.smith@example.com",
    grade: "G6",
    experience: "20 years",
    status: requestStatus.REJECTED,
    designation: "Principal Software Engineer",
    phone: "+1 9876543210",
    reportingManager: "Michael Johnson",
    projects: "PQR Corp, MNO Corp",
    requestStatusStep: 4,
  },
  {
    profile: {
      name: "David Wilson",
      profileImage:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtsSbrsoLNPyAUwVkiNfnQsf6d-xPwtXjDZ-NGyZxzHQ&s",
      employeeId: "2468135790",
    },
    id: 4,
    email: "david.wilson@example.com",
    grade: "G3",
    experience: "7 years",
    status: requestStatus.APPROVED,
    designation: "Software Engineer",
    phone: "+1 2345678901",
    reportingManager: "Sarah Thompson",
    projects: "LMN Corp, GHI Corp",
    requestStatusStep: 3,
  },
  {
    profile: {
      name: "Sarah Thompson",
      profileImage:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtsSbrsoLNPyAUwVkiNfnQsf6d-xPwtXjDZ-NGyZxzHQ&s",
      employeeId: "1357924680",
    },
    id: 5,
    email: "sarah.thompson@example.com",
    grade: "G7",
    experience: "22 years",
    status: requestStatus.OPEN,
    designation: "Lead Software Engineer",
    phone: "+1 3456789012",
    reportingManager: "Robert Davis",
    projects: "JKL Corp, DEF Corp",
    requestStatusStep: 2,
  },
  {
    profile: {
      name: "Sophia Thompson",
      profileImage: "https://example.com/profiles/sophiathompson.jpg",
      employeeId: "7359146208",
    },
    id: 11,
    email: "sophia.thompson@example.com",
    grade: "G4",
    experience: "11 years",
    status: requestStatus.OPEN,
    designation: "Senior Software Engineer",
    phone: "+1 9012345678",
    reportingManager: "Christopher Davis",
    projects: "ABC Corp, LMN Corp",
    requestStatusStep: 2,
  },
];
